elibrary/Areas/Administration/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class DashboardController : AdministrationDefaultController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

elibrary/Areas/Administration/Controllers/NumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using elibrary.Areas.Administration.Models;
using elibrary.Areas.Administration.Services;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class NumberController : AdministrationDefaultController
    {
        private NumberService _service;

        public NumberController(NumberService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _service.GetCollectionDTOAsync();

            return View(model);
        }

        public IActionResult Create() => View(new NumberDTO());

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Изменить";
            var model = await _service.GetDTOAsync(id);

            return View(nameof(Create), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(NumberDTO dto)
        {
            if (ModelState.IsValid)
            {
                await _service.Save(dto);
                //_flasher.Flash(FlashTypes.Success, "Данные сохранены");

                return RedirectToAction(nameof(Index));
            }

            ViewData["Title"] = "Изменить";
            return View(nameof(Create), dto);
        }
    }
}

elibrary/Areas/Administration/Views/Number/Create.cshtml
@model NumberDTO
@{
    ViewData["Title"] = " Добавление номера";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home">Главная</a></li>
    <li><a asp-action="Index" asp-controller="Dashboard" asp-area="Administration">Админ</a></li>
    <li><a asp-action="Index" asp-controller="Number" asp-area="Administration">Список номеров</a></li>
    <li class="active">@ViewData["Title"]</li>
</ol>

<h2>@ViewData["Title"]</h2>

<form asp-action="Edit">
    <div class="col col-md-4">
        <input type="hidden" asp-for="Id" />

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Date" class="control-label"></label>
            <input id="Date" name="Date" value="@DateTime.Now" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Sum" class="control-label"></label>
            <input asp-for="Sum" class="form-control" />
            <span asp-validation-for="Sum" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Balance" class="control-label"></label>
            <input asp-for="Balance" class="form-control" />
            <span asp-validation-for="Balance" class="text-danger"></span>
        </div>

        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</form>

elibrary/Areas/Administration/Views/Number/Index.cshtml
@model IEnumerable<NumberDTO>
@{
    ViewData["Title"] = " Список номеров ";
}

<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home" asp-area="">Главная</a></li>
    <li><a asp-action="Index" asp-controller="Dashboard" asp-area="Administration">Админ</a></li>
    <li class="active">@ViewData["Title"]</li>
</ol>

<h2>@ViewData["Title"]</h2>


<div class="panel panel-default">
    <div class="panel-heading">
        <authorize action="Create">
            <a asp-action="Create" class="btn btn-sm btn-success">
                <i class="glyphicon glyphicon-plus-sign"></i><span class="text">Добавить</span>
            </a>
        </authorize>
    </div>
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <th> Номер </th>
            <th> Время последнего заполнения</th>
            <th> Сумма последнего заполнения</th>
            <th> Остаток</th>
            <th> Изменить</th>
            <th> Удалить</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.PhoneNumber</td>
                <td>@item.Date</td>
                <td>@item.Sum</td>
                <td>@item.Balance</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@(item.Id)">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@(item.Id)">
                        <span class="glyphicon glyphicon-remove"></span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>