elibrary/Areas/Administration/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class DashboardController : AdministrationDefaultController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

elibrary/Areas/Administration/Controllers/NumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using elibrary.Areas.Administration.Models;
using elibrary.Areas.Administration.Services;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class NumberController : AdministrationDefaultController
    {
        private NumberService _service;

        public NumberController(NumberService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _service.GetCollectionDTOAsync();

            return View(model);
        }

        public IActionResult Create() => View(new NumberDTO());

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Изменить";
            var model = await _service.GetDTOAsync(id);

            return View(nameof(Create), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(NumberDTO dto)
        {
            if (ModelState.IsValid)
            {
                await _service.Save(dto);
                //_flasher.Flash(FlashTypes.Success, "Данные сохранены");

                return RedirectToAction(nameof(Index));
            }

            ViewData["Title"] = "Изменить";
            return View(nameof(Create), dto);
        }
    }
}

elibrary/Areas/Administration/Controllers/SellerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core.Flash;
using elibrary.Areas.Administration.Models;
using elibrary.Areas.Administration.Services;
using elibrary.Classes;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class SellerController : AdministrationDefaultController
    {
        private SellerService _service;
        private IFlasher _flasher;

        public SellerController(SellerService service, IFlasher flasher)
        {
            _service = service;
            _flasher = flasher;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _service.GetCollectionDTOAsync();

            return View(model);
        }

        public IActionResult Create() => View(new SellerDTO());

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Изменить";
            var model = await _service.GetDTOAsync(id);

            return View(nameof(Create), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            _flasher.Flash(FlashTypes.Success, "Данные удалены");
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(SellerDTO dto)
        {
            if (ModelState.IsValid)
            {
                await _service.Save(dto);
                _flasher.Flash(FlashTypes.Success, "Данные сохранены");
                return RedirectToAction(nameof(Index));
            }

            ViewData["Title"] = "Изменить";
            return View(nameof(Create), dto);
        }
    }
}

elibrary/Areas/Administration/Controllers/ShopController.cs
using System.Threading.Tasks;
using elibrary.Areas.Administration.Services;
using Microsoft.AspNetCore.Mvc;
using elibrary.Areas.Administration.Models;

namespace elibrary.Areas.Administration.Controllers
{
    public class ShopController : AdministrationDefaultController
    {
        private ShopService _service;

        public ShopController(ShopService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var model = await _service.GetCollectionDTOAsync();

            return View(model);
        }

        public IActionResult Create() => View(new ShopDTO());

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Изменить";
            var model = await _service.GetShopDTOAsync(id);

            return View(nameof(Create), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(ShopDTO dto)
        {
            if (ModelState.IsValid)
            {
                await _service.Save(dto);
                //_flasher.Flash(FlashTypes.Success, "Данные сохранены");

                return RedirectToAction(nameof(Index));
            }

            ViewData["Title"] = "Изменить";
            return View(nameof(Create), dto);
        }
    }
}

elibrary/Areas/Administration/Views/Dashboard/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Администрирование";
}
<ol class="breadcrumb">
    <li><a asp-action="Index" asp-controller="Home" asp-area="">Главная</a></li>
    <li class="active">@ViewData["Title"]</li>
</ol>

<div class="row">
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <a asp-area="Administration" asp-controller="Number" asp-action="Index" class="dh-button">
                    <span class="icon">
                        <i class="glyphicon glyphicon-phone"></i>
                    </span>
                    <div class="text">
                        <span class="title">Мои номера</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <a asp-area="Administration" asp-controller="Seller" asp-action="Index" class="dh-button">
                    <span class="icon">
                        <i class="glyphicon glyphicon-user"></i>
                    </span>
                    <div class="text">
                        <span class="title">Продавец</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card">
            <div class="card-body">
                <a asp-area="Administration" asp-controller="Shop" asp-action="Index" class="dh-button">
                    <span class="icon">
                        <i class="glyphicon glyphicon-shopping-cart"></i>
                    </span>
                    <div class="text">
                        <span class="title">Магазин</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>