elibrary/Areas/Administration/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace elibrary.Areas.Administration.Controllers
{
    public class DashboardController : AdministrationDefaultController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

elibrary/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using elibrary.Classes;
using elibrary.Data;
using elibrary.Models;
using elibrary.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace elibrary.Controllers
{
    public class ClientController : DefaultController
    {
        private ClientService _service;
        private ILogger<ClientController> _logger;

        public ClientController(ClientService clientService, ILogger<ClientController> logger)
        {
            _service = clientService;
            _logger = logger;
        }

        public async Task<IActionResult> Index(int? numberId, string dateStart = null, string dateEnd = null)
        {
            var ds = !string.IsNullOrEmpty(dateStart) ? DateTime.ParseExact(dateStart, "dd.MM.yyyy H:mm", System.Globalization.CultureInfo.CurrentCulture) : DateTime.Now.AddMonths(-2);
            var de = !string.IsNullOrEmpty(dateEnd) ? DateTime.ParseExact(dateEnd, "dd.MM.yyyy H:mm", System.Globalization.CultureInfo.CurrentCulture) : DateTime.Now;
            var nId = numberId ?? 0;

            try
            {
                var model = await _service.GetCollectionDTOAsync(ds, de, nId);

                ViewBag.DateStart = ds.ToString("dd.MM.yyyy H:mm");
                ViewBag.DateEnd = de.ToString("dd.MM.yyyy H:mm");
                ViewBag.NumberId= nId;
                ViewBag.Numbers = _service.GetNumbersAsync();

                return View(model);
            }
            catch (Exception ex)
            {
                _logger.LogError($"Упал в метод Index: {ex.Message}");
                return Redirect("/Home/Error");
            }
        }
        public IActionResult Create()
        {
            ViewData["Title"] = "Добавление записи";
            ViewBag.Shops = _service.GetShopsAsync();
            ViewBag.Sellers = _service.GetSellersAsync();
            ViewBag.Numbers = _service.GetNumbersAsync();
            return View(new Client() { Date = DateTime.Now});
        }

        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "Изменение записи";
            ViewBag.Shops = _service.GetShopsAsync();
            ViewBag.Sellers =  _service.GetSellersAsync();
            ViewBag.Numbers = _service.GetNumbersAsync();
            var model = await _service.GetDTOAsync(id);

            return View(nameof(Create), model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ActionName(nameof(Edit))]
        public async Task<IActionResult> EditPost(Client dto)
        {
            if (ModelState.IsValid)
            {
                await _service.Save(dto);
                //_flasher.Flash(FlashTypes.Success, "Данные сохранены");

                return RedirectToAction(nameof(Index));
            }
            ViewData["Title"] = "Изменение/Добавление записи";  
            ViewBag.Shops = _service.GetShopsAsync();
            ViewBag.Sellers = _service.GetSellersAsync();
            ViewBag.Numbers = _service.GetNumbersAsync();
            return View(nameof(Create), dto);
        }
    }
}

elibrary/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using elibrary.Models;
using Microsoft.AspNetCore.Authorization;
using elibrary.Classes;

namespace elibrary.Controllers
{
    public class HomeController : DefaultController
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

elibrary/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

elibrary/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

elibrary/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Главная страница";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Меню</h3>
    </div>
    <div class="panel-body">
        <a asp-area="Administration" asp-controller="Dashboard" asp-action="Index">
            <span class="icon">
                <i class="glyphicon glyphicon-user"></i>
            </span>
            <div class="text">
                <span class="title">Admin</span>
            </div>
        </a> 
        <a asp-area="" asp-controller="Client" asp-action="Index">
            <span class="icon">
                <i class="glyphicon glyphicon-user"></i>
            </span>
            <div class="text">
                <span class="title">Записи по клиентам</span>
            </div>
        </a>
    </div>
</div>